blog/bblog/urls.py
from django.urls import path
from . import views

app_name = 'bblog'

urlpatterns = [
    path(r'', views.post_list, name='list'), #全記事表示
    path('<int:pk>/', views.PostDetail, name='detail'), #記事詳細
    path('python/', views.List_Python, name='BigCategory_python'),#大カテゴリー　python
    path('docker/', views.List_docker, name='BigCategory_docker'),#大カテゴリーdocker

]

blog/composeblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bblog.urls")),
    path('markdownx/', include('markdownx.urls')),
]

blog/bblog/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.utils import timezone
import datetime
import os

# Create your models here.
class BigCategory(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    def get_latest_post(self):
        result = Post.objects.filter(
            category__parent=self).filter(
            is_publick=True).order_by('-created_at')[:5]
        return result

class SmallCategory(models.Model):
    """ 小カテゴリー """
    name = models.CharField(max_length=255)
    parent = models.ForeignKey(BigCategory, on_delete=models.PROTECT, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(
            category=self).filter(
            is_publick=True).order_by('-created_at')[:5]
        return result
    
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE, related_name="著者")
    title = models.CharField(max_length=50, verbose_name="タイトル")
    text = MarkdownxField(help_text='Markdown形式で書いてください。',verbose_name="本文")
    card_text = models.TextField(verbose_name='記事説明文',default="")
    bigCategory = models.ForeignKey(BigCategory, on_delete=models.PROTECT,  null=True, blank=True, related_name= "大カテゴリ")
    category = models.ForeignKey(SmallCategory, on_delete=models.PROTECT,  null=True, blank=True, related_name= "小カテゴリ")
    is_public = models.BooleanField(default=True, verbose_name='公開可能か')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_date = models.DateTimeField(auto_now=True,verbose_name="更新日時")
    published_date = models.DateField(blank=True,null=True, verbose_name="公開日時")

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def text_to_markdown(self):
        return markdownify(self.text)

    def text_card_markdown(self):
        return markdownify(self.card_text)

blog/bblog/views.py
from django.shortcuts import render
from django.views import  View
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.clickjacking import xframe_options_exempt
from django.http import Http404, HttpResponse
from django.views import generic

# Create your views here.
def paginate_queryset(request, queryset, count):

    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def post_list(request):
    posts = Post.objects.all()
    page_obj = paginate_queryset(request, posts, 12)
    print(page_obj.object_list)
    return render(request, 'bblog/blog.html', {
        'posts': posts,
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
    })


def PostDetail(request, pk):
    article = get_object_or_404(Post,id=pk)
    return render(request, 'bblog/article.html',{
        'article': article
    })

def List_Python(request):
   python_Category = Post.objects.filter(bigCategory__name="python")
   page_obj = paginate_queryset(request, python_Category, 1)
   print(page_obj.object_list)
   return render(request, 'bblog/python.html', {
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
                                })

def List_docker(request):
   docker_Category = Post.objects.filter(bigCategory__name='docker')
   page_obj = paginate_queryset(request, docker_Category, 1)
   print(page_obj.object_list)
   return render(request, 'bblog/docker.html', {
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
                                })

blog/bblog/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load app %}
<html lang="ja">
<head>

    <meta charset="UTF-8">
    <title>{% block title %}プログラミング備忘録{% endblock %}</title>
    <meta name="description" content="制作物や学んだことをアウトプットしていくブログ">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

</head>


<body>

<header >
    <div class="bg-img">
        <img src="{% static "images\W0RUS6FWBJ.jpg" %}" class="" width="100%" height="250" alt="表示">
        <p><a href="{% url 'bblog:list' %}" style="text-decoration:none; color: white;">プログラミング備忘録</a></p>
        <style>
            .bg-img
            {
                position: relative;
            }
            .bg-img p
            {
                position: absolute;
                color: aliceblue;
                font-size: 3.5rem;
                top: 35%;
                left: 3%;
                padding: 0.3rem 0.5rem;
                margin: 0;
            }
        </style>
    </div>

</header>
<div class="container_main wrapper">
    <div class="row">
    <main class="col-md-8 col-12" style="padding-top: 3rem;">
        {% block content %}
        {% endblock %}
    </main>

    <aside class="col-md-2 col-12" style="padding-top: 5rem; ">
        <ul class="list-group">
            <li class="list-group-item" style="background-color: #2e2d36;"><h3 class="sub_title" style="color: azure;"><strong>メインカテゴリー</strong></h3></li>
            <a href="{% url 'bblog:BigCategory_python' %}" class="list-group-item list-group-item-action"><h4>Python</h4></a>
            <a href="{% url 'bblog:BigCategory_docker' %}" class="list-group-item list-group-item-action"><h4>Docker</h4></a>
        </ul>
        
        
        
    </aside>

    </div>

</div>

<div class="paginator ">
    {% include 'bblog/Pagination.html' %}
</div>

<footer>

</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

</body>


</html>

blog/bblog/templates/bblog/Pagination.html
<nav aria-label=" Page navigation example text-center">
    <ul class="pagination " style="padding-top: 5rem; margin-left: 38rem;">
        <!-- 前へ の部分 -->
       {% if page_obj.has_previous %}
           <li class="page-item">
               <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                   <span aria-hidden="true">前え</span>
               </a>
           </li>
       {% endif %}
    
       <!-- 数字の部分 -->
       {% for num in page_obj.paginator.page_range %}
           {% if page_obj.number == num %}
               <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
           {% else %}
               <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
           {% endif %}
       {% endfor %}
    
       <!-- 次へ の部分 -->
       {% if page_obj.has_next %}
           <li class="page-item">
               <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                   <span aria-hidden="true">次へ</span>
               </a>
           </li>
       {% endif %}
    </ul>
</nav>

blog/bblog/templates/bblog/article.html
{% extends 'base.html' %}

{% load app %}
{% load static %}

{% block content %}

<article class="post-article" style="padding-top: 3rem; padding-left: 10rem; padding-right: 10rem;">
    <header class="post-info">
        <h2 class="post-title">{{  article.title  }}</h2>
        <p class="post-data">{{ article.updated_date }}</p>
    </header>

    <hr>

    <div class="markdown">
        <p>{{   article.text | markdown_to_html | safe }}</p>
    </div>
</article>

{% endblock %}

blog/bblog/templates/bblog/blog.html
{% extends "base.html" %}

{% load static %}
{% load app %}

{% block title %}
全体記事
{% endblock %}

<!--記事カード-->
{% block content %}
<div>
    {% for post in post_list %}
    <div class="card m-6" style="width: 50rem; margin-top: 2rem; margin-left: 20rem;">
        <div class="card-body">
            <h3 class="card-title"><a style="text-decoration:none; color: black;" href="{% url 'bblog:detail' post.id %}">{{ post.title }}</a></h3>
            <p class="card-text"><h5>{{ post.card_text }}</h5></p>
            <h6 class="card-subtitle mb-2 text-body-secondary">更新日時：{{ post.updated_date }}</h6>
            <p>{{ post.bigCategory }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

blog/bblog/templates/bblog/docker.html
{% extends "base.html" %}

{% load static %}
{% load app %}

{% block title %}
Docker
{% endblock %}

<!--記事カード-->
{% block content %}
<div>
    {% for do in post_list %}
    <div class="card m-6" style="width: 50rem; margin-top: 2rem; margin-left: 20rem;">
        <div class="card-body">
            <h3 class="card-title"><a style="text-decoration:none; color: black;" href="{% url 'bblog:detail' do.id %}">{{ do.title }}</a></h3>
            <p class="card-text"><h5>{{ do.card_text }}</h5></p>
            <h6 class="card-subtitle mb-2 text-body-secondary">更新日時：{{ do.updated_date }}</h6>
            <p>{{ do.bigCategory }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

blog/bblog/templates/bblog/python.html
{% extends "base.html" %}

{% load static %}
{% load app %}

{% block title %}
Python
{% endblock %}

<!--記事カード-->
{% block content %}
<div>
    {% for py in post_list %}
    <div class="card m-6" style="width: 50rem; margin-top: 2rem; margin-left: 20rem;">
        <div class="card-body">
            <h3 class="card-title"><a style="text-decoration:none; color: black;" href="{% url 'bblog:detail' py.id %}">{{ py.title }}</a></h3>
            <p class="card-text"><h5>{{ py.card_text }}</h5></p>
            <h6 class="card-subtitle mb-2 text-body-secondary">更新日時：{{ py.updated_date }}</h6>
            <p>{{ py.bigCategory }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}